### ISSUE TITLE
Typo in Image reward-distribution.png - Example 1: Reward Distribution

### ISSUE THREAD

**Issue by FranciscoAfra216** [Phala-Network/phala-wiki-next#100]
Direct link: https://wiki.phala.network/en-us/general/applications/delegation-example/

Under "Delegation" --> "Examples of Delegation" there is the image reward-distribution.png where we can see a typo on the rewards for Delegator A and B, it should be the opposite, delegator A gets the 1.6 PHA, not 3.2 PHA.

![image](https://user-images.githubusercontent.com/44093339/163439620-20ca78b8-67f1-47cc-a266-9462a5b339d3.png)

My Khala address: 43jngowNLTQhoEAFENUao77R27cfzNMT7jUzm9AKm3HS962E
Thanks for the tip ;)

**Comment by DavyChang** [comment]
hi, you can follow this topic to propose a tip https://forum.phala.network/t/topic/3211

**Comment by shelvenzhou** [comment]
Fixed
