### ISSUE TITLE
Redraw all the figures in the Wiki 

### ISSUE THREAD

**Issue by shelvenzhou** [Phala-Network/phala-wiki-next#27]
## Summary

Redraw all the figures into a unified style

**Comment by hauni97** [comment]
Also, use a unified style in icons when referring to Phala or third parties (social media, partners, etc.), such as Polkadot (Polkadot{.js}). 
- Ensure consistency across the Phala Brand

For example:
<img width="765" alt="Screenshot 2021-11-23 at 11 25 16" src="https://user-images.githubusercontent.com/37558304/143007817-0b56edc1-6ad6-4515-8925-408477d23cfc.png">
(/en-us/docs/khala-mining/khala-pre-mainnet-mining-guide/)

**Comment by hauni97** [comment]
Also adjust the design of the architecture shown in both Developer Rubrics:
/en-us/docs/developer/blockchain-detail/

**Comment by shelvenzhou** [comment]
Done.
