### ISSUE TITLE
Change the font. 

### ISSUE THREAD

**Issue by hauni97** [Phala-Network/phala-wiki-next#28]
TODO: Change the font globally in Doks to comply with Phala design and potentially reuse font of current wiki.
This is necessary prior to launching the new wiki.

**Comment by limichange** [comment]
Do you mean to make the new wiki font the same as the old one?

**Comment by hauni97** [comment]
Yes .

On Nov 18, 2021, at 4:50 AM, limichange ***@***.***> wrote:

﻿

Do you mean to make the new wiki font the same as the old one?

**Comment by hauni97** [comment]
@limichange if you have some spare time would you please add the same font as in the current wiki for now?

The current wiki uses san-serif Lato for headings and sans-serif Calibre for text according to the font inspector:

![image](https://user-images.githubusercontent.com/37558304/143427886-a70643eb-b458-4732-bb41-8ccd39cc2f53.png)
