### ISSUE TITLE
LaTeX formula exceed the page width

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-wiki-next#3]
Low priority.

![telegram-cloud-photo-size-5-6222040236507115011-y](https://user-images.githubusercontent.com/1343470/134307954-2c69b627-3eda-426a-9de4-1b54b5b9de80.jpg)

**Comment by limichange** [comment]
It has been fixed, now there is a scrollbar if the formula is too wide.
![image](https://user-images.githubusercontent.com/1947344/136646423-ee2477c0-2846-44fb-96c0-5412196088c5.png)
