### ISSUE TITLE
Add expanding & collapsing sections

### ISSUE THREAD

**Issue by hauni97** [Phala-Network/phala-wiki-next#33]
## Summary

This feature would improve readability and allow the reader to focus on what they need to read most.

### Basic example
<img src="https://user-images.githubusercontent.com/37558304/143010038-7c4dd32a-919d-480e-b1cb-7398f7069f46.png" height="500">

The reader can expand and collapse the respective sections. 

### Motivation

The reader could pick their platform (OS) and avoid verbosity when reading. Only the required content would be seen. 
Specifically relevant for:

- /en-us/docs/khala-mining/1-1-hardware-requirements/
- /en-us/docs/developer/run-a-local-development-network/

**Comment by shelvenzhou** [comment]
Closed with this PR #38 for tab demo
