### ISSUE TITLE
404. New Wiki cannot be loaded. See netlify preview. 

### ISSUE THREAD

**Issue by hauni97** [Phala-Network/phala-wiki-next#43]
## Description

Issue comes since new PR. After investigating any version before this commit: https://github.com/Phala-Network/phala-wiki-next/pull/41/commits/1d7f9c26f438c14652723cecbf66ac5d7f680364 seems to work.

### Steps to reproduce

This only appears when the npm server is restarted. 

### Expected result

Pages should load.

### Actual result

Also check current Netlify deployment, pages are not loaded.

404 error without any issues in the logs

![image](https://user-images.githubusercontent.com/37558304/144903944-24375c89-ba0b-4ec1-b792-784f16bf04ee.png)

![image](https://user-images.githubusercontent.com/37558304/144904015-6eadae48-66e5-4b33-b833-35cb131a868f.png)

### Environment

```
> @hyas/doks@0.3.4 precheck
> npm version

{
  '@hyas/doks': '0.3.4',
  npm: '8.1.0',
  node: '16.13.0',
  v8: '9.4.146.19-node.13',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.3.4 check
> exec-bin node_modules/.bin/hugo/hugo version
```

**Comment by limichange** [comment]
It may be caused by the removal of Chinese content, I fixed it, please pull the latest code to have a try.

**Comment by hauni97** [comment]
> It may be caused by the removal of Chinese content, I fixed it, please pull the latest code to have a try.

@limichange I can confirm the newest version works locally. The [netlify preview](https://phala-wiki-preview.netlify.app) works fine on Safari but occasionally breaks in the Brave browser, as an old version was still cached. Deleting the cache and cookies solved this as well. 

LGTM for deployment.
