### ISSUE TITLE
Adjust code block background 

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-wiki-next#5]
Now the background of code blocks in light mode is in a yellow tune. We should ask the designer to figure out how to deal with it.

![image](https://user-images.githubusercontent.com/1343470/134308287-f58d04c7-c869-4ef2-a8cf-c7dba6407b1e.png)

**Comment by limichange** [comment]
I've already given feedback to the designer, and I'm waiting for feedback.

**Comment by limichange** [comment]
Removed background color and updated the font color to `#EDA900`.

![telegram-cloud-photo-size-5-6274049060646268595-y](https://user-images.githubusercontent.com/1947344/136647781-5bea7239-1ea2-44b9-be3a-4eade93bac49.jpg)
