### ISSUE TITLE
Cannot switch language

### ISSUE THREAD

**Issue by shelvenzhou** [Phala-Network/phala-wiki-next#6]
## Description

try to switch to Chinese and get this

![image](https://user-images.githubusercontent.com/5029067/134309910-b876d27f-4339-4113-ae92-96f387d0cfeb.png)

**Comment by limichange** [comment]
Because we just have added English content, after we add all content from the old wiki website, all things will be fine.

**Comment by limichange** [comment]
Now there is no more content in Chinese, so I closed it now.
