### ISSUE TITLE
Learn -> Phala Blockchain-> Phala Blockchain Entities not showing

### ISSUE THREAD

**Issue by hauni97** [Phala-Network/phala-wiki-next#69]
## Description

https://wiki.phala.network/en-us/learn/phala-blockchain/blockchain-entities/ is not shown under Phala Blockchain. 
Probably requires a change in heading. 

### Steps to reproduce

This site can currently only be accessed when clicking on the hyperlink of Developer Blockchain entities. 

### Expected result

Should be shown under the Phala Blockchain in learn.

**Comment by shelvenzhou** [comment]
Fixed.
