### ISSUE TITLE
dead link / wrong redirects 

### ISSUE THREAD

**Issue by illyrianalien** [Phala-Network/phala-wiki-next#70]
## Description

Link redirects to the wiki site are returning 404 on github and on the phala.network domain most of the sublinks returns to: 

https://wiki.phala.network/en-us/general/phala-network/phala-network/

### Steps to reproduce

Trying this page: 

https://wiki.phala.network/en-us/docs/khala-mining/3-0-console/
https://wiki.phala.network/en-us/docs/khala-mining/4-0-faq/#confidence-level
https://wiki.phala.network/en-us/docs/phala-network/phala-network/
https://wiki.phala.network/en-us/docs/

### Expected result

Should be landing into the specified hyperlinks.

**Comment by hauni97** [comment]
@illyrianalien replace 'docs' with 'maintain' in all URLs and they should work. 
This is a result of our updated wiki. 

Aimed to be tackled in this PR https://github.com/Phala-Network/phala-wiki-next/pull/68

**Comment by illyrianalien** [comment]
@hauni97 
thanks a lot, will do!

**Comment by illyrianalien** [comment]
FYI: 

https://wiki.phala.network/en-us/maintain/khala-mining/ works fine. 

but for example 

https://wiki.phala.network/en-us/docs/khala-mining/4-2-how-to-fast-sync-node-use-snapshot/

to: 

https://wiki.phala.network/en-us/maintain/khala-mining/4-2-how-to-fast-sync-node-use-snapshot/ doesn't.

**Comment by hauni97** [comment]
> 

@illyrianalien, where did you find this link?
This (https://wiki.phala.network/en-us/maintain/khala-mining/4-2-how-to-fast-sync-node-use-snapshot/) is, in general deprecated, and we no longer recommend users to use a snapshot when setting up a miner.

**Comment by illyrianalien** [comment]
@hauni97 it was still crawled on search engines, then looked it up in the /content directory of the wiki here, then i saw it mentioned here: https://discord.com/channels/697726436211163147/756105753743458314/940186836280680458 which might have mislead me.

Thanks for the update! 

I could find all the remaining link via the /maintain
